### ISSUE TITLE
Why no iphone support?

### ISSUE THREAD

**Issue by juice500ml** [SGCSRelease/ReleaseApp#1]
제곧내

**Comment by tronze** [comment]
I think we will make Iphone Version later...

**Comment by JimJeon** [comment]
안드로이드 만들고 스위프트 즉석해서 배워서 이식할 계획입니당

**Comment by juice500ml** [comment]
cross-platform을 사용하는건 어때요? Adobe Phonegap이나 Xamarin 등등 많아요

**Comment by JimJeon** [comment]
@tronze 의 의견도 들어보아야겠지만 저 같은 경우에는 안드로이드 개발을 배워보자는 목적으로 이것을 시작한거라 처음은 그래도 android studio로 배우는게 편하다고 생각됩니당...
근데 platform을 바꾸는거면 초기인 지금 해야하는게 맞다고 생각되니 이 부분에 대해서는 좀 더 이야기를 나누어봐야겠군요

**Comment by tronze** [comment]
저도 안드로이드 복습과 스위프트 개발을 공부하려고 시작한거라 다른 툴보다는 xcode와 은드로이드 스튜디오를 사용하고 싶습니다!

**Comment by minhoryang** [comment]
@juice500ml 쥬스야 우리가 만들까?

Cross-Platform은 역사가 깊어요.
Apache Phonegap프로젝트는 Adobe를 거쳐서 Cordova프로젝트로 새 이름을 얻었구요.
웹페이지로 기능을 구현하면, 이를 앱으로 감싸줘요.
(앱->웹뷰->웹페이지(기능))

어제 릴리즈된 Ionic2는 이 Cordova에 Angular2로 짜여진 앱느낌나는 UI Framework를 제공하는데요. 이를 이용하면 금방 쉬운 앱을 짤 수 있어요.

**Comment by juice500ml** [comment]
@minhoryang 기획 들어보고요! 어떤건지 궁금하네요~ 사실 awesome-title이랑 묶어놓고 싶은 생각이 많아요..!

**Comment by JimJeon** [comment]
Xamarin - C#
Cordova - HTML/CSS/JS
Android Studio - Java
이렇게 개발 언어가 다르군요
지금 windows app 개발 때문에 c#을 배우고 싶은데 마침 Xamarin으로 개발하게 되면 저는 대찬성입니다.

하지만 우선 각각의 장단점을 짚고 넘어가고 싶군요...

**Comment by tronze** [comment]
제가 예전에 FlashBuilder 등을 사용해본적 있었는데, 초기 단계여서인지는 잘 모르겠지만 커스터마이징이 자유롭지 못하다 느껴서 안드로이드 스튜디오랑 Xcode를 공부하려 했었습니다. 혹시 가능하시다면 안드로이드 스튜디오와 Xcode를 Cross-platform과 비교했을 때 장단점에 대해 설명 부탁드리겠습니다! 감사합니다!

**Comment by juice500ml** [comment]
플랫폼: code once, deploy everywhere
네이티브: maximum functionality & detail
느낌입니다. 각자의 장점은 서로의 단점!

2017. 1. 26. 오후 8:44에 "tronze" <notifications@github.com>님이 작성:

**Comment by JimJeon** [comment]
우선 아이디어 노트 작성해놓은거 이슈로 옮기겠습니다.

**Comment by tronze** [comment]
찾아본 결과 지금 발전한 cross-platform상태에서는 시스템적으로 건드리는 부분만 아니면 전부 구현 가능한 것으로 보입니다! 결론적으로 Xamarin으로 개발해볼까 합니다.

**Comment by minhoryang** [comment]
자마린 안써봐서 ㅠㅠㅠㅠ 지켜볼게요:)

**Comment by JimJeon** [comment]
@minhoryang 열심히해보겠습니다!! ㅋㅋ

**Comment by JimJeon** [comment]
Xamarin 개발시작!
