### ISSUE TITLE
start_page, StartActivity 관련

### ISSUE THREAD

**Issue by JimJeon** [SGCSRelease/ReleaseApp#2]
이 부분은 login을 하는 부분이니까 login_page와 LoginActivity로 바꾸는것이 좋지 않을까요?

... 너무 사소한 부분인가요? ㅋㅋ

**Comment by tronze** [comment]
Evernote 보셨으면 아시겠지만 제가 start_page와 합쳐놓은거에요!

만약 로그인 되있으면 바로 main_page로 넘어갈 생각했습니다!

**Comment by JimJeon** [comment]
editted.
